/**
 * PROJECT: Clay County Directory Engine - Main Layout
 * VERSION: 1.34 (JSON SYNC)
 * FEATURES: 93% Width, JSON fetch, A-M Structure, Color Lock.
 */

let masterData = []; // This will hold our JSON data
const imageRepo = "https://raw.githubusercontent.com/KFruti88/images/main/";

// --- MASTER TOWN COLOR PALETTE (COLOR LOCK) ---
const townStyles = {
    "Flora": { bg: "#0c0b82", text: "#fe4f00" },
    "Louisville": { bg: "#010101", text: "#eb1c24" },
    "North Clay": { bg: "#010101", text: "#eb1c24" },
    "Clay City": { bg: "#0c30f0", text: "#8a8a88" },
    "Xenia": { bg: "#000000", text: "#fdb813" },
    "Sailor Springs": { bg: "#000000", text: "#a020f0" },
    "Clay County": { bg: "#333333", text: "#ffffff" }
};

const catEmojis = {
    "Bars": "🍺", "Emergency": "🚨", "Church": "⛪", "Post Office": "📬", 
    "Restaurants": "🍴", "Retail": "🛒", "Shopping": "🛍️", "Manufacturing": "🏗️", 
    "Industry": "🏭", "Financial Services": "💰", "Healthcare": "🏥", 
    "Gas Station": "⛽", "Internet": "🌐", "Support Services": "🛠️", 
    "Professional Services": "💼"
};

document.addEventListener('DOMContentLoaded', () => {
    updateHeaderDate(); 
    fetchDirectoryData();
    getLocalWeather();
    
    // HEARTBEAT: Auto-sync every 5 mins
    setInterval(() => {
        console.log("Live Sync: Refreshing JSON data...");
        fetchDirectoryData();
    }, 300000); 
});

function updateHeaderDate() {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    const headerInfo = document.getElementById('header-info');
    if (headerInfo) headerInfo.innerText = `VOL. 1 — NO. ${now.getMonth() + 1} | ${dateStr}`;
}

async function fetchDirectoryData() {
    try {
        // Fetch the JSON file generated by Python
        const response = await fetch('directory.json?v=' + new Date().getTime());
        masterData = await response.json();
        renderDirectoryGrid(masterData);
    } catch (error) {
        console.error("Error loading JSON directory:", error);
    }
}

function getSmartLogo(imageID, name) {
    let fileName = imageID ? imageID.trim() : "";
    if (!fileName && name) fileName = name.toLowerCase().replace(/['\s]/g, "");
    const placeholder = `https://via.placeholder.com/150?text=Logo+Pending`;
    return `<img src="${imageRepo}${fileName}.jpeg" style="max-height:100%; max-width:100%; object-fit:contain;" alt="${name}" 
            onerror="this.onerror=null; this.src='${imageRepo}${fileName}.png'; this.onerror=function(){this.src='${placeholder}'};">`;
}

function getBizFontSize(name) {
    if (name.length > 35) return "0.95rem"; 
    if (name.length > 22) return "1.1rem";    
    return "1.3rem";                        
}

function renderDirectoryGrid(data) {
    const grid = document.getElementById('directory-grid');
    if (!grid) return;
    
    // --- FORCE 93% WIDTH AND CENTERING ---
    grid.style.width = "93%";
    grid.style.margin = "0 auto";
    grid.style.display = "grid";
    grid.style.gridTemplateColumns = "repeat(auto-fit, minmax(300px, 1fr))";
    grid.style.gap = "20px";

    const tierOrder = { "premium": 1, "plus": 2, "basic": 3 };

    grid.innerHTML = data.sort((a, b) => {
        const tA = (a.tier || "basic").toLowerCase();
        const tB = (b.tier || "basic").toLowerCase();
        return (tierOrder[tA] || 4) - (tierOrder[tB] || 4) || a.town.localeCompare(b.town);
    }).map(biz => {
        const tierL = (biz.tier || "basic").toLowerCase();
        const style = townStyles[biz.town] || { bg: "#333333", text: "#ffffff" };
        const bizFontSize = getBizFontSize(biz.name);
        
        // Modal Trigger logic
        let clickAction = (tierL === 'premium' || (biz.coupon && biz.coupon !== "N/A")) 
                        ? `onclick="openFullModal('${biz.name.replace(/'/g, "\\'")}')"` : "";

        return `
        <div class="card ${tierL}" ${clickAction} style="cursor: ${clickAction ? 'pointer' : 'default'}; height: 450px; display: flex; flex-direction: column; overflow: hidden; border: 1px solid #000; background: #fff; position: relative;">
            <div class="tier-badge" style="position:absolute; top:5px; right:5px; font-size: 0.7rem; background:rgba(0,0,0,0.1); padding:2px 5px; border-radius:3px;">${biz.tier}</div> 
            
            <div class="logo-box" style="height: 140px; display: flex; align-items: center; justify-content: center; padding: 15px;">
                ${getSmartLogo(biz.image_id, biz.name)}
            </div>

            <div class="town-bar" style="background-color: ${style.bg}; color: ${style.text}; height: 35px; display: flex; align-items: center; justify-content: center; text-transform: uppercase; font-weight: bold; font-size: 0.95rem; border-top: 2px solid #000; border-bottom: 2px solid #000;">
                ${biz.town}
            </div> 

            <div class="biz-name" style="height: 90px; display: flex; align-items: center; justify-content: center; text-align: center; font-weight: 800; padding: 10px; font-size: ${bizFontSize}; line-height: 1.2; font-family: 'Times New Roman', serif;">
                ${biz.name}
            </div> 
            
            <div style="flex-grow: 1; display: flex; flex-direction: column; justify-content: space-around; padding: 10px; background: transparent;">
                ${(tierL === 'premium' || tierL === 'plus') ? `<div class="biz-phone" style="text-align:center; font-weight:bold; font-size: 1.1rem; color: #0c30f0;">📞 ${biz.phone}</div>` : ''}
                <div class="cat-text" style="text-align:center; font-size: 0.9rem; color: #444;">
                    ${catEmojis[biz.category] || "📁"} ${biz.category}
                </div> 
            </div>
        </div>`;
    }).join('');
}

async function getLocalWeather() {
    const weatherBox = document.getElementById('weather-box');
    if (!weatherBox) return;
    try {
        const response = await fetch('https://api.open-meteo.com/v1/forecast?latitude=38.66&longitude=-88.48&current_weather=true');
        const data = await response.json();
        if (data.current_weather) {
            weatherBox.innerHTML = ` | 🌡️ Flora: ${Math.round((data.current_weather.temperature * 9/5) + 32)}°F`;
        }
    } catch (e) { console.log("Weather failed"); }
}
