/**
 * 1. PROJECT CONFIGURATION
 */
let masterData = []; 
const imageRepo = "https://raw.githubusercontent.com/KFruti88/images/main/";
const baseCsvUrl = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRDgQs5fH6y8PWw9zJ7_3237SB2lxlsx8Gnw8o8xvTr94vVtWwzs6qqidajKbPepQDS36GNo97bX_4b/pub?gid=0&single=true&output=csv";
const couponImg = "https://raw.githubusercontent.com/KFruti88/images/main/Coupon.png";

/**
 * 2. MASTER CATEGORY LIST
 */
const catEmojis = {
    "Agriculture": "🚜", "Auto Repair": "🔧", "Bars/Saloon": "🍺", "Beauty Salon": "💇",
    "Carwash": "🧼", "Church": "⛪", "Community": "👥", "Education & Health": "📚",
    "Government": "🏛️", "Healthcare": "🏥", "Manufacturing": "🏗️", "Medical": "🏥",
    "Professional Services": "💼", "Restaurants": "🍴", "Stores": "🛍️", 
    "USPS/Post Office": "📬", "Non-Profit": "📝"
};

/**
 * 3. CATEGORY MAPPING LOGIC
 * Replaces your "Searching..." formula text with clean labels.
 */
function mapCategory(raw) {
    if (!raw || raw === "Searching..." || raw === "N/A") return "Professional Services";
    const val = raw.toLowerCase().trim();

    if (val.includes("city hall") || val.includes("court") || val.includes("government")) return "Government";
    if (val.includes("restaurant") || val.includes("bar") || val.includes("saloon")) return "Restaurants";
    if (val.includes("medical") || val.includes("healthcare") || val.includes("hospital")) return "Healthcare";
    if (val.includes("flower") || val.includes("pottery") || val.includes("store") || val.includes("handmade")) return "Stores";
    if (val.includes("legion") || val.includes("non-profit") || val.includes("charity")) return "Non-Profit";
    if (val.includes("factory") || val.includes("warehouse") || val.includes("manufacturing")) return "Manufacturing";
    
    return raw; 
}

/**
 * 4. INITIALIZATION
 */
document.addEventListener("DOMContentLoaded", () => {
    updateNewspaperHeader();
    loadDirectory();
});

async function loadDirectory() {
    const cacheBuster = new Date().getTime();
    Papa.parse(`${baseCsvUrl}&cb=${cacheBuster}`, {
        download: true,
        header: true,
        skipEmptyLines: true,
        complete: (results) => {
            // Formula Header Cleanup: Ensures "Town" is found even with spaces
            const cleaned = results.data.map(row => {
                const newRow = {};
                Object.keys(row).forEach(key => {
                    newRow[key.trim()] = row[key]; 
                });
                return newRow;
            });

            // Filter out empty rows generated by ARRAYFORMULA
            masterData = cleaned.filter(row => row.Name && row.Name !== "" && row.Name !== "Searching...");
            
            generateCategoryDropdown();
            renderCards(masterData);
        }
    });
}

/**
 * 5. RENDERING ENGINE
 */
function renderCards(data) {
    const grid = document.getElementById('directory-grid');
    if (!grid) return;

    grid.innerHTML = data.map(biz => {
        const tier = (biz.Tier || biz.Teir || 'basic').toLowerCase();
        
        // Handle "UNKNOWN" Town issue from formula
        let town = (biz.Town || biz.town || "").trim();
        if (town === "" || town === "Searching...") town = "Clay County";
        
        const townClass = town.toLowerCase().replace(/\s+/g, '-');
        const displayCat = mapCategory(biz.Category || biz.category);

        return `
            <div class="card ${tier}" ${tier === 'premium' ? `onclick="window.location.href='profile.html?id=${encodeURIComponent(biz['Image ID'])}'"` : ''}>
                <div class="tier-badge">${tier}</div>
                <div class="logo-box">${getSmartImage(biz['Image ID'], biz.Name)}</div>
                <div class="town-bar ${townClass}-bar">${town}</div>
                <h2>${biz.Name}</h2>
                <div style="margin-top: auto; font-style: italic; font-weight: bold;">
                    ${catEmojis[displayCat] || "📁"} ${displayCat}
                </div>
            </div>`;
    }).join('');
}

function getSmartImage(id, bizName) {
    const placeholder = `https://via.placeholder.com/150?text=Logo+Pending`;
    if (!id || id === "N/A") return `<img src="${placeholder}">`;
    return `<img src="${imageRepo}${id.trim().toLowerCase()}.jpeg" onerror="this.src='${placeholder}'">`;
}

function generateCategoryDropdown() {
    const catSelect = document.getElementById('cat-select');
    if (!catSelect) return;
    catSelect.innerHTML = '<option value="All">📂 All Industries</option>';
    Object.keys(catEmojis).sort().forEach(cat => {
        const option = document.createElement('option');
        option.value = cat;
        option.textContent = `${catEmojis[cat]} ${cat}`;
        catSelect.appendChild(option);
    });
}

function updateNewspaperHeader() {
    const header = document.getElementById('header-info');
    if(header) header.innerText = `VOL. 1 | ${new Date().toLocaleDateString()}`;
}
